---
- name: Load distro-specific vars
  include_vars: "{{item}}"
  with_first_found:
    - files:
       - "{{ ansible_distribution }}.yml"
       - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
       - "{{ ansible_os_family }}.yml"
       - "main.yml"

- name: Define container_type unless forced
  set_fact:
    container_type: "{{ _container_type }}"
  when: not container_type is defined

- name: Include platform specific variables
  include_vars: "{{ container_type }}.yml"

- include: install.yml
  when: service_state != "absent"
- include: uninstall.yml
  when: service_state == "absent"
